[google-drive]
type = drive
scope = drive
token = {"access_token":"ya29.a0Aa7pCA-T8Rg4Es6wbZxIc_cOeMZjB8q04v77NDuPXj3DKoOTVY9cm6jJmVJ_2I00R28vdfTFH7HOpzd98YLY5Omt88p558ta060RSXZbAPcJoPOTse9nPyrcX21uabRo3BO8O9hAGlJuCHfjCPiPWjABD1iBSt5CpWhsb4sUGu-ZGytxBVpJzmdTi7LKBlQ0OMdjd03FgQaCgYKAS0SARISFQHGX2MihGiMIcGDMP59AjgSxszi7w0209","token_type":"Bearer","refresh_token":"1//03XtE4R2z_m4rCgYIARAAGAMSNwF-L9Ir5RHalpI_vaiPGxiUvV65kSsKmzoiI87girFtg8YQIas-2fxmHT3WEaASrrzFnDnuQeU","expiry":"2025-12-27T19:01:29.414552297+01:00"}

